In [13]:
import numpy as np # arrays & loading data
import tensorflow as tf # arrays & loading data
from tensorflow.keras.models import Sequential  # model type that we will use
from tensorflow.keras.layers import Dense # we will use Dense layers

# suppress warnings
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)

In [55]:
# unpickle the data from the batch file in the CIFAR-10 dataset
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict
# save the data as a dictionary
dict = unpickle("cifar-10-batches-py\\data_batch_1")

# split the data using the keys
labels = np.array(pickle[b'labels'])
data = np.array(pickle[b'data'])

# form a column vector where only 0 and 1 are kept ( we need binary classification)
labels_zero_or_one = np.where((labels<2),labels,-1)
labels_zero_or_one = labels_zero_or_one.reshape(-1,1) 

# concatanate the labels column form above to the data
data_concatanated = np.concatenate((data,labels_zero_or_one),axis=1)

# keep only the rows that have 0 or 1 as labels (those with -1 as labels are not important now)
data_final= data_concatanated[data_concatanated[:,-1]!=-1]
print(data_final)
print(data_final.shape)

[[170 168 177 ...  78  80   1]
 [159 150 153 ...  17  19   1]
 [202 202 204 ... 243 243   0]
 ...
 [116 120 126 ...  84  81   1]
 [ 71  60  74 ...  69  68   1]
 [250 254 211 ... 255 254   1]]
(1979, 3073)


In [56]:
X = data_final[:,:-1] # forming the input and output 
y = data_final[:,-1]

y = np.expand_dims(y, axis=1) # make y 2D - the commands later will require it
