In [7]:
import numpy as np # arrays & loading data
import tensorflow as tf # arrays & loading data
from tensorflow.keras.models import Sequential  # model type that we will use
from tensorflow.keras.layers import Dense # we will use Dense layers

# suppress warnings
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)

In [8]:
# loading all the data
data = np.loadtxt('./diabetes_data.csv', delimiter=',', skiprows=1)
print(data)

[[40.  1.  0. ...  1.  1.  1.]
 [58.  1.  0. ...  1.  0.  1.]
 [41.  1.  1. ...  1.  0.  1.]
 ...
 [58.  0.  1. ...  0.  1.  1.]
 [32.  0.  0. ...  1.  0.  0.]
 [42.  1.  0. ...  0.  0.  0.]]


In [13]:
X = data[:,:-1] # forming the input and output 
y = data[:,-1]

y = np.expand_dims(y, axis=1) # make y 2D - the commands later will require it
print(X[:5])
print(y[:5])

[[40.  1.  0.  1.  0.  1.  0.  0.  0.  1.  0.  1.  0.  1.  1.  1.]
 [58.  1.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.  0.  1.  0.]
 [41.  1.  1.  0.  0.  1.  1.  0.  0.  1.  0.  1.  0.  1.  1.  0.]
 [45.  1.  0.  0.  1.  1.  1.  1.  0.  1.  0.  1.  0.  0.  0.  0.]
 [60.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [12]:
# split into training , cross validation and test sets
from sklearn.model_selection import train_test_split 

# TRAINING SET - 60%
X_train, X_temporary, y_train, y_temporary = train_test_split(X, y, test_size=0.40, random_state=1)

# the rest of 40% - CV SET(20%) and TEST SET(20%)
X_cv, X_test, y_cv, y_test = train_test_split(X_temporary, y_temporary, test_size=0.50, random_state=1)
del X_temporary, y_temporary

print(f"training input shape:{X_train.shape}")
print(f"training output shape:{y_train.shape}")
print(f"cv input shape:{X_cv.shape}")
print(f"cv output shape:{y_cv.shape}")
print(f"test input shape:{X_test.shape}")
print(f"test output shape:{y_test.shape}")

training input shape:(312, 16)
training output shape:(312, 1)
cv input shape:(104, 16)
cv output shape:(104, 1)
test input shape:(104, 16)
test output shape:(104, 1)


In [14]:
# sequential model structure

# CHANGE TO CONVOLUTIONAL
model= Sequential(
    [
        tf.keras.Input(shape=(16,)), # input size (each patient has 16 features)
        Dense(10,activation="sigmoid", name="layer1"),
        Dense(5,activation="sigmoid", name="layer2"),
        Dense(1,activation="sigmoid", name="layer3"),
    ], name="binary_model"
)

In [15]:
# see details about the activation of every layer and the form of the w and b parameters
model.summary()

Model: "binary_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (None, 10)                  │             170 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer2 (Dense)                       │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer3 (Dense)                       │ (None, 1)                   │               6 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 231 (924.00 B)

 Trainable params: 231 (924.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:

# define loss and optimizer of the Adam's algorithm
model.compile(
    # this is similar to gradient descent, but it is a much improved version
    loss=tf.keras.losses.BinaryCrossentropy(), # BC - binary class 
    optimizer=tf.keras.optimizers.Adam(0.01), # preimplemented optimizer
)

In [18]:
# train the model "epochs" times
model.fit(
    X_train, y_train,
    epochs = 30
)

Epoch 1/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7246  
Epoch 2/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.6706  
Epoch 3/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.6539  
Epoch 4/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6485 
Epoch 5/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.6211  
Epoch 6/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5967 
Epoch 7/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.5274  
Epoch 8/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.5104  
Epoch 9/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4350 
Epoch 10/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4201 
Epoch 11/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.3586  
Epoch 12/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3259 
Epoch 13/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.2540  
Epoch 14/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - loss: 0.2527
Epoch 15/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 0.2635  
Ep

In [19]:
# fraction of misclassified outputs in the TRAINING SET
y_predicted = model.predict(X_train)
y_predicted = tf.math.sigmoid(y_predicted) # classify above or below the threshold
# classic way of calculating the error in a classification case
y_predicted = np.where(y_predicted>=0.5,1,0)
error = np.mean(y_predicted != y_train) # arithmetic mean, where the numerator is the count of wrong predictions
print(f"Training Set Classification Error: {error}")

# do the same for CV set
y_predicted = model.predict(X_cv)
y_predicted = tf.math.sigmoid(y_predicted) 
y_predicted = np.where(y_predicted>=0.5,1,0)
error2 = np.mean(y_predicted != y_cv) 
print(f"CV Set Classification Error: {error2}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Training Set Classification Error: 0.3942307692307692
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step  
CV Set Classification Error: 0.38461538461538464
